name: CI build with NPM

on:
  push:
  workflow_dispatch:

jobs:
  ci_build_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM Clean Install
        run: npm ci
      - name: Build React App
        run: npm run build
